### ISSUE TITLE
Exclude IP (Domain), run in background 

### ISSUE THREAD

**Issue by Doimatcuabautroi** [kayrus/ingress-terraform#4]
Hello guy, I love your tun2socks code, but I cannot create issue to your project so I create here.
As the tittle, can you add these features to you project ( https://github.com/kayrus/go-tun2socks)
Dear.

**Comment by kayrus** [comment]
I opened an ability to submit issues in https://github.com/kayrus/go-tun2socks
Please clarify what do you mean under excluding the domain or IP. This functionality is already supported.
As for the background mode, I don't really want to do this, since you can daemonize every app using systemd. I also don't think that user-end app should be daemonized.
